### ISSUE TITLE
HTTP Upload NIP-96 Compatibility

### ISSUE THREAD

**Issue by xeruf** [servuscms/servus#14]
Servus looks like exactly what I want - a self-hosted all-in-one package for my travel blog, cause I especially want an archive of images and running a separate [void.cat](https://git.v0l.io/Kieran/void.cat/issues/74) instance alongside my relay has proven to be a hassle.
Is the Blossom Server NIP-96 compatible though, so that I can upload images from other clients, or can that only happen via the own API / admin interface for now?

**Comment by ibz** [comment]
I added NIP-96 compatibility in the last release. Feel free to open other issues if it doesn't work with your client for some reason.
