### ISSUE TITLE
Set port and disable HTTPS (HTTP only mode)

### ISSUE THREAD

**Issue by IngwiePhoenix** [servuscms/servus#7]
Hello there!

I have been trying to find a way to "host" my own Nostr blog and stumbled over this while browsing awesome-nostr. So I immediately cloned and compiled it on my server - all good so far. But I couldn't seem to find a hint in the README about how to disable HTTPS support. Reason being that I already use Caddy and take advantage of it's auto-provisioning for certs with HTTP and DNS (CloudFlare) challenge and storing them in Redis to link another Caddy instance to the same certs.

Hence I would like to know how to do this. :) The rest is easy; I can "change" the location of the `sites` folder by setting PWD in my SystemD unit - though it'd be nice if the base path could be specified in the future.

Thank you for your hard work!

Kind regards,
Ingwie

**Comment by ibz** [comment]
Woah! I should probably add a flag to disable HTTPS, indeed. I don't know why I never thought of that.

Does it work for you otherwise? You are probably the first user that came so far... it is quite rough and not very user friendly still...

**Comment by ibz** [comment]
Done!

You can now set the port using `-p`.

Also, if you don't pass `--ssl-acme` or `-ssl-acme-production` or `--ssl-cert` it will be HTTP only!

**Comment by IngwiePhoenix** [comment]
Good morning!
Sorry for my late reply - I will give it a spin and edit this answer once I have some results. :)
